import "bootstrap-icons/font/bootstrap-icons.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./src/css/style.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import "./src/script/components/app-bar.js";
import "./src/script/components/search-bar.js";
import "./src/script/components/add-btn.js";
import "./src/script/components/item.js";
import "./src/script/components/item-list.js";
import "./src/script/components/item-form.js";
import "./src/script/components/stock-form.js";
import "./src/script/components/custom-modal.js";
import main from "./src/script/view/main.js";
document.addEventListener("DOMContentLoaded", main);
